import { Brief } from '../../../../../../types';

export const brief: Brief[] = [
  {
    "question": "What is a group in mathematics?",
    "questionExplanation": "",
    "answer": "**A group** is a set G equipped with a binary operation * that satisfies four properties: closure, associativity, the existence of an identity element, and the existence of inverse elements. A group can be finite or infinite, depending on the number of elements in the set."
  },
  {
    "question": "What is the difference between a monoid and a group?",
    "questionExplanation": "",
    "answer": "**A monoid** is a set with an associative binary operation and an identity element, but it does not require inverse elements. A **group**, on the other hand, includes all properties of a monoid but also requires that every element has an inverse."
  },
  {
    "question": "What is an Abelian group?",
    "questionExplanation": "",
    "answer": "**An Abelian group** (or commutative group) is a group in which the binary operation is commutative. This means that for any two elements a and b in the group, the equation a * b = b * a holds. Examples include the set of integers under addition."
  },
  {
    "question": "What is the order of an element in a group?",
    "questionExplanation": "",
    "answer": "The **order of an element a** in a group G is the smallest positive integer n such that a^n equals the identity element of the group. If no such integer exists, the element is said to have infinite order."
  },
  {
    "question": "What is a cyclic group?",
    "questionExplanation": "",
    "answer": "A **cyclic group** is a group that can be generated by a single element. This means that all elements of the group can be written as powers of a single element called a generator. If the group has a finite order n, it contains elements {e, g, g^2, ..., g^(n-1)}."
  }
];
